### ISSUE TITLE
Breaking plugin-hub changes

### ISSUE THREAD

**Issue by abextm** [andham97/play-time#1]
As of runelite/plugin-hub#725 this plugin will no longer build because you for accidentally committed [the package script](https://github.com/andham97/play-time/blob/master/package.gradle) to this repo. We will start to enforce a maximum line length of roughly 100 characters on all build files to make it more difficult to hide malicious plugins.

**Comment by andham97** [comment]
> As of [runelite/plugin-hub#725](https://github.com/runelite/plugin-hub/pull/725) this plugin will no longer build because you for accidentally committed [the package script](https://github.com/andham97/play-time/blob/master/package.gradle) to this repo. We will start to enforce a maximum line length of roughly 100 characters on all build files to make it more difficult to hide malicious plugins.

To resolve this, will I only need to remove the package.gradle file from the repo, or format it to the 100 characters per line?

**Comment by abextm** [comment]
There is no reason to have this file in your repo, so you can just remove it.
